#!/usr/bin/env bash

PROJECTPATH="."
MESSAGE="Install Laravel"
QUIET=false
DEVELOP=false
AUTH=false
NODE=true
# Uses CODE_EDITOR from .zshrc (cursor or code)
CODEEDITOR="/usr/local/bin/${CODE_EDITOR:-code}"
BROWSER=""
LINK=false
SECURE=false
FRONTEND="vue"
CREATE_DATABASE=true
DB_USERNAME="root"
DB_PASSWORD=""
