# NPM
# --openssl-legacy-provider
alias n='npm'
alias nv='npm --version'
alias nh='npm -l'
alias ni='npm install'
alias na='npm install --save'
alias nad='npm install --save-dev'
alias nl='npm list'
alias nu='npm update'
alias nrm='npm uninstall'
alias nf='npm search'
alias nod='npm outdated'

alias nga='npm install -g'
alias ngu='npm update -g'
alias ngrm='npm uninstall -g'

alias nr='npm run'
alias np='npm run prod'
alias nd='npm run dev'
alias nw='npm run watch'
alias nt='npm run test'
alias ntw='npm run test:watch'
alias ns='npm serve'
alias nb='npm run build'
# alias nsu='brew upgrade yarn'

# Volta
alias vt='volta'
alias vtv='volta --version'
alias vth='volta --help'
alias vta='volta install'
alias vtl='volta list'
alias vtlc='volta list --current'
alias vtld='volta list --default'
alias vtrm='volta uninstall'
alias vtp='volta pin'
